// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-MuAdeNT3quSLiLwlAWdCMi5VSmEeoQ',
    appId: '1:794880012939:web:c269b9d6a4dfddfb6a1a8e',
    messagingSenderId: '794880012939',
    projectId: 'carbonayak-62777',
    authDomain: 'carbonayak-62777.firebaseapp.com',
    storageBucket: 'carbonayak-62777.appspot.com',
    measurementId: 'G-VR2VVK8VDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1bP9Y6T_o2z_WBk1_qsSF___VsK9sWZU',
    appId: '1:794880012939:android:d7ee67f88339ff4b6a1a8e',
    messagingSenderId: '794880012939',
    projectId: 'carbonayak-62777',
    storageBucket: 'carbonayak-62777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV10rcOkyGF0lwtuqj6Nha7koquF1xBb8',
    appId: '1:794880012939:ios:b637ad9746b74af16a1a8e',
    messagingSenderId: '794880012939',
    projectId: 'carbonayak-62777',
    storageBucket: 'carbonayak-62777.appspot.com',
    iosBundleId: 'com.example.carbonayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV10rcOkyGF0lwtuqj6Nha7koquF1xBb8',
    appId: '1:794880012939:ios:b637ad9746b74af16a1a8e',
    messagingSenderId: '794880012939',
    projectId: 'carbonayak-62777',
    storageBucket: 'carbonayak-62777.appspot.com',
    iosBundleId: 'com.example.carbonayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg-MuAdeNT3quSLiLwlAWdCMi5VSmEeoQ',
    appId: '1:794880012939:web:823bdcc5910cad236a1a8e',
    messagingSenderId: '794880012939',
    projectId: 'carbonayak-62777',
    authDomain: 'carbonayak-62777.firebaseapp.com',
    storageBucket: 'carbonayak-62777.appspot.com',
    measurementId: 'G-RHJJTESLZD',
  );
}
